"""add automation scheduling

Revision ID: 5fa273e839c8
Revises: 7747b40ebe71
Create Date: 2026-09-13 01:36:00.595586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa273e839c8'
down_revision: Union[str, Sequence[str], None] = '7747b40ebe71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automations', sa.Column('schedule_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('automations', sa.Column('schedule_cron', sa.String(length=100), nullable=True))
    op.add_column('automations', sa.Column('schedule_timezone', sa.String(length=100), nullable=False, server_default="UTC"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automations', 'schedule_timezone')
    op.drop_column('automations', 'schedule_cron')
    op.drop_column('automations', 'schedule_enabled')
    # ### end Alembic commands ###
