"""add step execution attempt number

Revision ID: 8b81a7b58e05
Revises: d682d554f548
Create Date: 2026-09-14 14:08:48.505551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b81a7b58e05'
down_revision: Union[str, Sequence[str], None] = 'd682d554f548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('step_executions', sa.Column('attempt_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('step_executions', 'attempt_number')
    # ### end Alembic commands ###
