"""add execution artifacts

Revision ID: d19b84d5e258
Revises: 8b81a7b58e05
Create Date: 2026-09-15 00:45:18.034001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19b84d5e258'
down_revision: Union[str, Sequence[str], None] = '8b81a7b58e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('step_execution_id', sa.Integer(), nullable=True),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['automation_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_execution_id'], ['step_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_execution_id'), 'artifacts', ['execution_id'], unique=False)
    op.create_index(op.f('ix_artifacts_step_execution_id'), 'artifacts', ['step_execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artifacts_step_execution_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_execution_id'), table_name='artifacts')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
