"""add automation next run time

Revision ID: d64292031578
Revises: dc1b8b6a6ffa
Create Date: 2026-09-13 17:38:55.189040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd64292031578'
down_revision: Union[str, Sequence[str], None] = 'dc1b8b6a6ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automations', sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automations', 'next_run_at')
    # ### end Alembic commands ###
