"""add retry configuration to automation steps

Revision ID: d682d554f548
Revises: a16decde7310
Create Date: 2026-09-14 13:56:40.923282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd682d554f548'
down_revision: Union[str, Sequence[str], None] = 'a16decde7310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automation_steps', sa.Column('retry_enabled', sa.Boolean(), nullable=False))
    op.add_column('automation_steps', sa.Column('max_retries', sa.Integer(), nullable=False))
    op.add_column('automation_steps', sa.Column('retry_delay_seconds', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('automation_steps', 'retry_delay_seconds')
    op.drop_column('automation_steps', 'max_retries')
    op.drop_column('automation_steps', 'retry_enabled')
    # ### end Alembic commands ###
